apiVersion: v1
kind: Pod
metadata:
  name: mtkpi-pod
  namespace: default
  labels:
    app: mtkpi
spec:
  serviceAccountName: pentest-sa  # Указываем созданный сервисный аккаунт
  containers:
  - name: mtkpi-container
    image: steer09/mtkpi:v1.5
    ports:
    - containerPort: 7681
    resources:  # Ресурсы контейнера
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"

